apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::381491976987:role/eksctl-expense-1-nodegroup-expense-NodeInstanceRole-iYVm1Uzkykj1
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::381491976987:user/venkat
      username: venkat    
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-12T14:47:35Z"
  name: aws-auth
  namespace: kube-system
  uid: e5af4de6-f8e9-4cf3-8ad0-2b3f8d236fe4  # dont delete this 


# kubectl get configmap aws-auth -n kube-system -o yaml
