apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::381491976987:role/eksctl-expense-1-nodegroup-expense-NodeInstanceRole-AdQlwhGw4z34
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::381491976987:user/venkat
      username: venkat        
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-15T08:35:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1230"
  uid: c0fbd2a3-b513-4962-9de9-9293cb0a35d0



# kubectl get configmap aws-auth -n kube-system -o yaml
